name: Sync EcoMobile Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  sync-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # IMPORTANT : Empêche le bot de s'imposer

      - name: Configure Git identity
        run: |
          git config user.name "Xybronix"
          git config user.email "xybronix@gmail.com"

      - name: Split frontend subtree
        run: |
          git subtree split --prefix=frontend -b frontend-split

      - name: Push to EcoMobile-frontend
        run: |
          git push https://Xybronix:${{ secrets.ECOMOBILE_SYNC_TOKEN }}@github.com/Xybronix/EcoMobile-frontend.git frontend-split:main --force