import type { Bike, Ride, Payment, Incident, Notification } from './mobile-types';

export const mockBikes: Bike[] = [
  {
    id: 'bike-001',
    name: 'Freebike Sport #001',
    status: 'available',
    battery: 85,
    location: {
      lat: 5.345317,
      lng: -4.024429,
      address: 'Plateau, Abidjan',
    },
    lastUpdate: new Date(),
    model: 'Sport X1',
    qrCode: 'FB-BIKE-001',
    pricePerMinute: 50,
    features: ['GPS', 'Panier', 'Antivol', 'Lumières LED'],
  },
  {
    id: 'bike-002',
    name: 'Freebike City #002',
    status: 'available',
    battery: 92,
    location: {
      lat: 5.350000,
      lng: -4.020000,
      address: 'Marcory, Abidjan',
    },
    lastUpdate: new Date(),
    model: 'City Comfort',
    qrCode: 'FB-BIKE-002',
    pricePerMinute: 45,
    features: ['GPS', 'Panier', 'Siège confort'],
  },
  {
    id: 'bike-003',
    name: 'Freebike Pro #003',
    status: 'available',
    battery: 78,
    location: {
      lat: 5.340000,
      lng: -4.030000,
      address: 'Cocody, Abidjan',
    },
    lastUpdate: new Date(),
    model: 'Pro Max',
    qrCode: 'FB-BIKE-003',
    pricePerMinute: 60,
    features: ['GPS', 'Suspension', 'Écran LCD', 'Porte-bagages'],
  },
  {
    id: 'bike-004',
    name: 'Freebike Sport #004',
    status: 'in-use',
    battery: 65,
    location: {
      lat: 5.355000,
      lng: -4.025000,
      address: 'Treichville, Abidjan',
    },
    lastUpdate: new Date(),
    model: 'Sport X1',
    qrCode: 'FB-BIKE-004',
    pricePerMinute: 50,
    features: ['GPS', 'Panier', 'Antivol', 'Lumières LED'],
  },
  {
    id: 'bike-005',
    name: 'Freebike City #005',
    status: 'available',
    battery: 95,
    location: {
      lat: 5.348000,
      lng: -4.022000,
      address: 'Adjamé, Abidjan',
    },
    lastUpdate: new Date(),
    model: 'City Comfort',
    qrCode: 'FB-BIKE-005',
    pricePerMinute: 45,
    features: ['GPS', 'Panier', 'Siège confort'],
  },
];

export const mockRides: Ride[] = [
  {
    id: 'ride-001',
    bikeId: 'bike-001',
    bikeName: 'Freebike Sport #001',
    userId: 'user-001',
    startTime: new Date(Date.now() - 3600000),
    endTime: new Date(Date.now() - 1800000),
    startLocation: {
      lat: 5.345317,
      lng: -4.024429,
      address: 'Plateau, Abidjan',
    },
    endLocation: {
      lat: 5.350000,
      lng: -4.020000,
      address: 'Marcory, Abidjan',
    },
    distance: 2.5,
    duration: 30,
    cost: 1500,
    status: 'completed',
  },
  {
    id: 'ride-002',
    bikeId: 'bike-002',
    bikeName: 'Freebike City #002',
    userId: 'user-001',
    startTime: new Date(Date.now() - 86400000),
    endTime: new Date(Date.now() - 84600000),
    startLocation: {
      lat: 5.340000,
      lng: -4.030000,
      address: 'Cocody, Abidjan',
    },
    endLocation: {
      lat: 5.345317,
      lng: -4.024429,
      address: 'Plateau, Abidjan',
    },
    distance: 1.8,
    duration: 25,
    cost: 1125,
    status: 'completed',
  },
  {
    id: 'ride-003',
    bikeId: 'bike-003',
    bikeName: 'Freebike Pro #003',
    userId: 'user-001',
    startTime: new Date(Date.now() - 172800000),
    endTime: new Date(Date.now() - 169200000),
    startLocation: {
      lat: 5.355000,
      lng: -4.025000,
      address: 'Treichville, Abidjan',
    },
    endLocation: {
      lat: 5.348000,
      lng: -4.022000,
      address: 'Adjamé, Abidjan',
    },
    distance: 3.2,
    duration: 45,
    cost: 2700,
    status: 'completed',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay-001',
    userId: 'user-001',
    type: 'ride',
    amount: 1500,
    currency: 'XOF',
    method: 'wallet',
    status: 'completed',
    createdAt: new Date(Date.now() - 1800000),
    completedAt: new Date(Date.now() - 1800000),
    reference: 'FB-PAY-001',
    details: {
      rideId: 'ride-001',
    },
  },
  {
    id: 'pay-002',
    userId: 'user-001',
    type: 'wallet-topup',
    amount: 10000,
    currency: 'XOF',
    method: 'orange-money',
    status: 'completed',
    createdAt: new Date(Date.now() - 86400000),
    completedAt: new Date(Date.now() - 86400000),
    reference: 'FB-PAY-002',
    details: {
      phoneNumber: '+225 07 12 34 56 78',
      transactionId: 'OM123456789',
    },
  },
  {
    id: 'pay-003',
    userId: 'user-001',
    type: 'ride',
    amount: 1125,
    currency: 'XOF',
    method: 'wallet',
    status: 'completed',
    createdAt: new Date(Date.now() - 84600000),
    completedAt: new Date(Date.now() - 84600000),
    reference: 'FB-PAY-003',
    details: {
      rideId: 'ride-002',
    },
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    userId: 'user-001',
    bikeId: 'bike-001',
    rideId: 'ride-001',
    type: 'technical',
    severity: 'medium',
    description: 'Le frein avant ne fonctionne pas correctement',
    location: {
      lat: 5.350000,
      lng: -4.020000,
      address: 'Marcory, Abidjan',
    },
    images: [],
    status: 'investigating',
    createdAt: new Date(Date.now() - 3600000),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    type: 'ride',
    title: 'Trajet terminé',
    message: 'Votre trajet de 30 minutes est terminé. Coût: 1500 XOF',
    read: false,
    createdAt: new Date(Date.now() - 1800000),
    data: {
      rideId: 'ride-001',
    },
  },
  {
    id: 'notif-002',
    userId: 'user-001',
    type: 'payment',
    title: 'Recharge réussie',
    message: 'Votre compte a été crédité de 10000 XOF',
    read: true,
    createdAt: new Date(Date.now() - 86400000),
    data: {
      paymentId: 'pay-002',
    },
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    type: 'promotion',
    title: 'Offre spéciale !',
    message: '20% de réduction sur votre prochain trajet ce weekend',
    read: false,
    createdAt: new Date(Date.now() - 172800000),
  },
];
